### ISSUE TITLE
Remove polling loop

### ISSUE THREAD

**Issue by phxnsharp** [ansys/api-eigen-example#52]
This line of code uses a number of code smells:
 - Polling loop
 - Direct access to an external object's private members
 - Sleep

https://github.com/ansys/api-eigen-example/blob/108085fcaa860a9d1e27abbdc561c160a98e09e3/src/ansys/eigen/python/grpc/client.py#L49

It would be cleaner to use the [Future's public API](https://grpc.github.io/grpc/python/grpc.html#grpc.Future.result) (guessing based on internet search. I have not tried this). e.g `self._state.result(timeout)`

**Comment by RobPasMue** [comment]
Hi @phxnsharp! You are totally right, this may solve the problem. I'll try it out as soon as I can. Thanks for pointing this out!

**Comment by RobPasMue** [comment]
I've been doing some tests with the Future API... Doesn't look like it's going to solve our problem. I'll keep testing.

**Comment by RobPasMue** [comment]
Found it 😄 I was just not doing it right... setting up PR and assigning you as reviewer @phxnsharp
